#!/bin/sh
# Run this to setup the sources
: ${AUTORECONF=autoreconf --force --install}
: ${INTLTOOLIZE=autopoint --force && intltoolize --force --automake}
: ${LIBTOOLIZE=libtoolize --force --copy}

func_echo()
{
	echo
	echo -e "\033[0;32m*\033[0m $@"
	echo
}

func_echo "Running: $LIBTOOLIZE"
$LIBTOOLIZE

func_echo "Running: $AUTORECONF"
LIBTOOLIZE=true AUTOPOINT=$INTLTOOLIZE $AUTORECONF
